'use client'
import { FormEvent,useState } from 'react'
import type { DirectoryMember } from '@/lib/members/directory'
import type { ProjectApplication } from '@/lib/projects/applications'
import type { ProjectWorkspace } from '@/lib/projects/workspace'

async function jsonFetch(url:string,init:RequestInit){const response=await fetch(url,init);const body=await response.json();if(!response.ok)throw new Error(body.error??'Request failed.');return body}
export function MilestoneManager({projectId,milestones}:{projectId:string;milestones:ProjectWorkspace['milestones']}){const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{await jsonFetch(`/api/member/projects/${projectId}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({action:'milestone',title:form.get('title'),description:form.get('description'),status:form.get('status'),dueDate:form.get('dueDate'),sortOrder:100})});setMessage('Milestone added.');window.setTimeout(()=>window.location.reload(),400)}catch(error){setMessage(error instanceof Error?error.message:'Could not save milestone.')}finally{setBusy(false)}}return <section className="workspace-section"><div className="workspace-section__head"><div><p className="eyebrow">Plan</p><h2>Milestones</h2></div></div>{milestones.length?<div className="milestone-list">{milestones.map(m=><article key={m.id}><span className={`status-pill status-${m.status.toLowerCase()}`}>{m.status.replaceAll('_',' ')}</span><div><strong>{m.title}</strong>{m.description&&<p>{m.description}</p>}{m.dueDate&&<small>Due {new Date(`${m.dueDate}T12:00:00`).toLocaleDateString()}</small>}</div></article>)}</div>:<p className="empty-copy">No milestones yet.</p>}<form className="workspace-inline-form" onSubmit={submit}><label>Milestone<input name="title" required minLength={2}/></label><label>Status<select name="status" defaultValue="TODO"><option>TODO</option><option>IN_PROGRESS</option><option>BLOCKED</option><option>DONE</option></select></label><label>Due date<input name="dueDate" type="date"/></label><label className="workspace-span">Description<textarea name="description" rows={2}/></label><button className="button--cardinal" disabled={busy}>{busy?'Saving…':'Add milestone'}</button>{message&&<span role="status">{message}</span>}</form></section>}

export function RosterManager({projectId,roster}:{projectId:string;roster:ProjectWorkspace['roster']}){const[busy,setBusy]=useState('');async function remove(userId:string){if(!confirm('Remove this member from the project team?'))return;setBusy(userId);try{await jsonFetch(`/api/member/projects/${projectId}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({action:'remove-member',userId})});window.location.reload()}finally{setBusy('')}}return <section className="workspace-section"><p className="eyebrow">Team</p><h2>Roster</h2><div className="workspace-roster">{roster.map(member=><article key={member.userId}><div className="member-card__initial" aria-hidden="true">{member.displayName.slice(0,1).toUpperCase()}</div><div><strong>{member.displayName}</strong><small>{member.role==='LEAD'?'Project Lead':'Team member'}</small></div>{member.role!=='LEAD'&&<button disabled={busy===member.userId} onClick={()=>void remove(member.userId)}>Remove</button>}</article>)}</div></section>}

export function ApplicationReviewList({applications}:{applications:ProjectApplication[]}){const[busy,setBusy]=useState('');const[message,setMessage]=useState('');async function decide(id:string,decision:'ACCEPT'|'REJECT'){setBusy(id);try{await jsonFetch('/api/member/project-applications',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({applicationId:id,decision})});setMessage(decision==='ACCEPT'?'Applicant added to the team.':'Application rejected.');window.setTimeout(()=>window.location.reload(),400)}catch(error){setMessage(error instanceof Error?error.message:'Decision failed.')}finally{setBusy('')}}if(!applications.length)return null;return <section className="workspace-section"><p className="eyebrow">Recruiting</p><h2>Applications</h2>{message&&<p className="member-inline-notice" role="status">{message}</p>}<div className="workspace-applications">{applications.map(app=><article className="content-card" key={app.id}><h3>{app.applicantName??'OEC member'}</h3><p>{app.motivation}</p><div className="tag-row">{app.skills.map(skill=><span key={skill}>{skill}</span>)}</div><div className="system-actions"><button className="button--cardinal" disabled={busy===app.id} onClick={()=>void decide(app.id,'ACCEPT')}>Accept</button><button disabled={busy===app.id} onClick={()=>void decide(app.id,'REJECT')}>Reject</button></div></article>)}</div></section>}

export function TeamInviteForm({projectId,members,roster}:{projectId:string;members:DirectoryMember[];roster:ProjectWorkspace['roster']}){const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const existing=new Set(roster.map(r=>r.userId));const options=members.filter(m=>m.displayName&&!existing.has(m.userId));async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const formElement=event.currentTarget;const form=new FormData(formElement);try{await jsonFetch('/api/member/project-invitations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId,invitedUserId:form.get('memberId'),message:form.get('message')})});setMessage('Invitation sent. The member must accept before joining.');formElement.reset()}catch(error){setMessage(error instanceof Error?error.message:'Could not send invitation.')}finally{setBusy(false)}}return <section className="workspace-section"><p className="eyebrow">Build the team</p><h2>Invite an approved member</h2><p>Only members who chose to appear in the private directory are shown here.</p>{options.length?<form className="workspace-inline-form" onSubmit={submit}><label>Member<select name="memberId" required defaultValue=""><option value="" disabled>Select a member</option>{options.map(m=><option key={m.userId} value={m.userId}>{m.displayName}{m.major?` · ${m.major}`:''}</option>)}</select></label><label className="workspace-span">Message<textarea name="message" rows={2} placeholder="What would you like them to work on?"/></label><button className="button--cardinal" disabled={busy}>{busy?'Sending…':'Send invitation'}</button>{message&&<span role="status">{message}</span>}</form>:<p className="empty-copy">No additional visible members to invite right now.</p>}</section>}

export function TeamUpdateForm({projectId}:{projectId:string}){const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{await jsonFetch(`/api/member/projects/${projectId}/updates`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:form.get('title'),summary:form.get('summary'),body:form.get('body'),milestone:form.get('milestone'),updateDate:form.get('updateDate')})});setMessage('Update submitted for Admin review. It is not public yet.');event.currentTarget.reset();window.setTimeout(()=>window.location.reload(),500)}catch(error){setMessage(error instanceof Error?error.message:'Could not submit update.')}finally{setBusy(false)}}return <section className="workspace-section"><p className="eyebrow">Document the work</p><h2>Submit a project update</h2><p>This creates a private draft. An Admin must review it before it can be published publicly.</p><form className="workspace-inline-form" onSubmit={submit}><label>Title<input name="title" minLength={3} required/></label><label>Date<input name="updateDate" type="date"/></label><label className="workspace-span">Summary<textarea name="summary" rows={3} minLength={10}/></label><label className="workspace-span">Full update<textarea name="body" rows={6}/></label><label>Milestone label<input name="milestone"/></label><button className="button--cardinal" disabled={busy}>{busy?'Submitting…':'Submit for review'}</button>{message&&<span role="status">{message}</span>}</form></section>}
