import 'server-only'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { sendTransactionalEmail } from '@/lib/email/client'
import { memberSiteOrigin } from '@/lib/email/siteOrigin'
import { projectApplicationDecisionEmail } from '@/lib/email/templates'
export type ProjectApplication={id:string;projectId:string;projectTitle:string;applicantUserId:string;applicantName?:string;applicantEmail?:string;motivation:string;skills:string[];status:'PENDING'|'ACCEPTED'|'REJECTED'|'WITHDRAWN';decisionNote?:string|null;createdAt:string}
const compact=(value:unknown)=>Array.from(new Set((Array.isArray(value)?value:[]).map(v=>String(v).trim()).filter(Boolean))).slice(0,20)
export async function applyToProject(input:{projectId:string;motivation:string;skills:string[]}){const motivation=input.motivation.trim();if(motivation.length<10)throw new Error('APPLICATION_MOTIVATION_REQUIRED');const s=await createSupabaseServerClient();const{data,error}=await s.rpc('submit_project_application',{p_project_id:input.projectId,p_motivation:motivation,p_skills:compact(input.skills)});if(error)throw new Error(error.message);return data}
export async function reviewProjectApplication(input:{applicationId:string;decision:'ACCEPT'|'REJECT';note?:string}){const s=await createSupabaseServerClient();const{data,error}=await s.rpc('review_project_application',{p_application_id:input.applicationId,p_decision:input.decision,p_note:input.note?.trim()||null});if(error)throw new Error(error.message);const result=data as any;if(result?.applicantEmail){const base=memberSiteOrigin();const accepted=result.status==='ACCEPTED';await sendTransactionalEmail({to:result.applicantEmail,message:projectApplicationDecisionEmail({memberName:result.applicantName??'there',projectTitle:result.projectTitle??'OEC project',decision:accepted?'ACCEPTED':'REJECTED',actionUrl:accepted?`${base}/member/teams/${result.projectId}`:`${base}/member/applications`,note:input.note}),required:false})}return data}
export async function getApplicationTarget(projectId:string){const s=await createSupabaseServerClient();const{data,error}=await s.from('projects').select('id,title,summary,recruiting').eq('id',projectId).eq('publication_state','published').maybeSingle();if(error||!data||!data.recruiting)return null;return data}
async function attachProjects(rows:any[]){const s=await createSupabaseServerClient();const ids=Array.from(new Set(rows.map(r=>r.project_id)));const{data:projects}=ids.length?await s.from('projects').select('id,title,slug').in('id',ids):{data:[] as any[]};const map=new Map((projects??[]).map((p:any)=>[p.id,p]));return rows.map(r=>({id:r.id,projectId:r.project_id,projectTitle:map.get(r.project_id)?.title??'Project',applicantUserId:r.applicant_user_id,motivation:r.motivation,skills:r.skills??[],status:r.status,decisionNote:r.decision_note,createdAt:r.created_at})) as ProjectApplication[]}
export async function listMyProjectApplications(userId:string){const s=await createSupabaseServerClient();const{data,error}=await s.from('project_applications').select('*').eq('applicant_user_id',userId).order('created_at',{ascending:false});if(error)throw new Error(error.message);return attachProjects(data??[])}
export async function listProjectApplications(projectId:string){const s=await createSupabaseServerClient();const{data,error}=await s.rpc('list_project_applications_for_lead',{p_project_id:projectId});if(error)throw new Error(error.message);return(data??[]).map((r:any)=>({id:r.id,projectId:r.project_id,projectTitle:'',applicantUserId:r.applicant_user_id,applicantName:r.applicant_name,motivation:r.motivation,skills:r.skills??[],status:r.status,decisionNote:r.decision_note,createdAt:r.created_at})) as ProjectApplication[]}
export async function listAdminProjectApplications(){const s=await createSupabaseServerClient();const{data,error}=await s.from('project_applications').select('*').eq('status','PENDING').order('created_at',{ascending:true});if(error)throw new Error(error.message);const raw=data??[];const rows=await attachProjects(raw);const ids=raw.map(row=>row.applicant_user_id);const{data:members}=ids.length?await s.from('member_profiles').select('user_id,display_name,oberlin_email').in('user_id',ids):{data:[] as any[]};const map=new Map((members??[]).map((m:any)=>[m.user_id,m]));return rows.map(row=>({...row,applicantName:map.get(row.applicantUserId)?.display_name,applicantEmail:map.get(row.applicantUserId)?.oberlin_email}))}
export async function withdrawProjectApplication(applicationId:string){const s=await createSupabaseServerClient();const{data,error}=await s.rpc('withdraw_project_application',{p_application_id:applicationId});if(error)throw new Error(error.message);return data}
