import 'server-only'
import { z } from 'zod'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { normalizeProjectProposalInput, reviewProjectProposal, type ProjectProposalStatus, type ProposalApprovalResult, type ProposalRejectionResult, type ProposalReviewDeps } from './proposals'
import { sendTransactionalEmail } from '@/lib/email/client'
import { projectProposalReviewEmail } from '@/lib/email/templates'

export type ProjectProposalSummary={id:string;proposerUserId:string;proposerName?:string;proposerEmail?:string;title:string;problem:string;goal:string;summary:string;disciplines:string[];recruitingNeeds:string;links:string[];status:ProjectProposalStatus;adminFeedback:string|null;approvedProjectId:string|null;createdAt:string;reviewedAt:string|null}
const map=(r:any):ProjectProposalSummary=>({id:r.id,proposerUserId:r.proposer_user_id,title:r.title,problem:r.problem,goal:r.goal,summary:r.summary??'',disciplines:r.disciplines??[],recruitingNeeds:r.recruiting_needs??'',links:Array.isArray(r.links)?r.links:[],status:r.status,adminFeedback:r.admin_feedback??null,approvedProjectId:r.approved_project_id??null,createdAt:r.created_at,reviewedAt:r.reviewed_at??null})

async function sendReviewEmail(result:ProposalApprovalResult|ProposalRejectionResult,feedback?:string){if(!result.email)return;const approved=result.status==='APPROVED';const base=process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/,'')??'';const actionUrl=approved&&'projectId'in result?`${base}/member/teams/${result.projectId}`:`${base}/member/proposals`;await sendTransactionalEmail({to:result.email,message:projectProposalReviewEmail({memberName:result.displayName??'there',projectTitle:result.title??'Project proposal',decision:approved?'APPROVED':'REJECTED',feedback,actionUrl}),required:false})}

export async function submitProjectProposal(userId:string,input:Record<string,unknown>){const proposal=normalizeProjectProposalInput(input);const teamId=input.teamId ? z.string().uuid().parse(input.teamId) : null;const s=await createSupabaseServerClient();const{data,error}=await s.from('project_proposals').insert({proposer_user_id:userId,team_id:teamId,title:proposal.title,problem:proposal.problem,goal:proposal.goal,summary:proposal.summary,disciplines:proposal.disciplines,recruiting_needs:proposal.recruitingNeeds,links:proposal.links,status:'PENDING'}).select('*').single();if(error||!data)throw new Error(`PROJECT_PROPOSAL_CREATE_FAILED:${error?.message??'unknown'}`);return map(data)}
export async function listMyProjectProposals(userId:string){const s=await createSupabaseServerClient();const{data,error}=await s.from('project_proposals').select('*').eq('proposer_user_id',userId).order('created_at',{ascending:false});if(error)throw new Error(`PROJECT_PROPOSALS_LOAD_FAILED:${error.message}`);return(data??[]).map(map)}
export async function listPendingProjectProposals(){const s=createSupabaseAdminClient();const{data,error}=await s.from('project_proposals').select('*').eq('status','PENDING').order('created_at',{ascending:true});if(error)throw new Error(`PROJECT_PROPOSALS_LOAD_FAILED:${error.message}`);const rows=(data??[]).map(map);const ids=Array.from(new Set(rows.map(r=>r.proposerUserId)));const{data:members}=ids.length?await s.from('member_profiles').select('user_id,display_name,oberlin_email').in('user_id',ids):{data:[] as any[]};const memberMap=new Map((members??[]).map((m:any)=>[m.user_id,m]));return rows.map(row=>({...row,proposerName:memberMap.get(row.proposerUserId)?.display_name,proposerEmail:memberMap.get(row.proposerUserId)?.oberlin_email}))}
function reviewDeps():ProposalReviewDeps{const s=createSupabaseAdminClient();return{approve:async input=>{const{data,error}=await s.rpc('approve_project_proposal',{p_proposal_id:input.proposalId,p_reviewer_id:input.reviewerId,p_feedback:input.feedback?.trim()||null});if(error)throw new Error(error.message);return data as ProposalApprovalResult},reject:async input=>{const{data,error}=await s.rpc('reject_project_proposal',{p_proposal_id:input.proposalId,p_reviewer_id:input.reviewerId,p_feedback:input.feedback?.trim()||null});if(error)throw new Error(error.message);return data as ProposalRejectionResult}}}
export async function reviewServerProjectProposal(input:{proposalId:string;decision:string;feedback?:string},reviewerId:string){const result=await reviewProjectProposal({...input,reviewerId},reviewDeps());await sendReviewEmail(result,input.feedback);return result}
