import 'server-only'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { sendTransactionalEmail } from '@/lib/email/client'
import { memberSiteOrigin } from '@/lib/email/siteOrigin'
import { projectTeamInvitationEmail } from '@/lib/email/templates'
export type TeamInvite={id:string;projectId:string;projectTitle:string;invitedUserId:string;inviterUserId:string;inviterName?:string;message:string;status:string;expiresAt:string;createdAt:string}
export async function inviteProjectMember(input:{projectId:string;invitedUserId:string;message?:string},inviterName:string){const s=await createSupabaseServerClient();const{data,error}=await s.rpc('create_project_team_invite',{p_project_id:input.projectId,p_invited_user_id:input.invitedUserId,p_message:input.message?.trim()||''});if(error)throw new Error(error.message);const result=data as any;if(result?.invitedEmail){const base=memberSiteOrigin();await sendTransactionalEmail({to:result.invitedEmail,message:projectTeamInvitationEmail({inviteeName:result.invitedName??'there',projectTitle:result.projectTitle??'OEC project',inviterName,message:input.message,actionUrl:`${base}/member/invitations`}),required:false})}return data}
export async function respondToTeamInvite(input:{inviteId:string;decision:'ACCEPT'|'DECLINE'}){const s=await createSupabaseServerClient();const{data,error}=await s.rpc('respond_project_team_invite',{p_invite_id:input.inviteId,p_decision:input.decision});if(error)throw new Error(error.message);return data}
export async function listMyTeamInvites(_userId:string):Promise<TeamInvite[]>{const s=await createSupabaseServerClient();const{data,error}=await s.rpc('list_my_project_team_invites');if(error)throw new Error(error.message);return(data??[]).map((r:any)=>({id:r.id,projectId:r.project_id,projectTitle:r.project_title??'Project',invitedUserId:r.invited_user_id,inviterUserId:r.invited_by_user_id,inviterName:r.inviter_name,message:r.message,status:r.status,expiresAt:r.expires_at,createdAt:r.created_at}))}
