import 'server-only'
import type { AdminRole } from '@/lib/permissions/types'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { assertTeamUpdatePublicationAllowed, normalizeTeamUpdateDraft } from './workspacePolicy'
import { sendTransactionalEmail } from '@/lib/email/client'
import { projectUpdateReviewEmail } from '@/lib/email/templates'
import { memberSiteOrigin } from '@/lib/email/siteOrigin'

export type WorkspaceSummary={projectId:string;title:string;slug:string;projectStatus:string;publicationState:string;membershipRole:'LEAD'|'MEMBER';recruiting:boolean}
export type MilestoneStatus='TODO'|'IN_PROGRESS'|'BLOCKED'|'DONE'
export type TeamPostKind='UPDATE'|'WIN'|'BLOCKER'|'QUESTION'
export type ProjectWorkspace={
  me:string
  project:{id:string;title:string;slug:string;summary:string;status:string;publicationState:string;recruiting:boolean;startedAt:string|null;nextStep:string;githubUrl:string;externalUrl:string}
  myRole:'LEAD'|'MEMBER'
  roster:Array<{userId:string;displayName:string;role:'LEAD'|'MEMBER';joinedAt:string}>
  milestones:Array<{id:string;title:string;description:string;status:MilestoneStatus;dueDate:string|null;sortOrder:number;assigneeUserId:string|null;assigneeName:string|null;completedAt:string|null}>
  updates:Array<{id:string;title:string;summary:string;body:string;milestone:string;updateDate:string|null;reviewStatus:string;reviewFeedback:string|null;submittedAt:string;submittedBy:string;publicationState:string}>
  kickoff:{message:string;meetingAt:string|null;meetingLocation:string;createdAt:string}|null
  posts:Array<{id:string;kind:TeamPostKind;body:string;authorUserId:string|null;authorName:string;officer:boolean;createdAt:string}>
  links:Array<{id:string;label:string;url:string;addedBy:string|null}>
}
export type ProjectOverview={projectId:string;title:string;role:'LEAD'|'MEMBER';status:string;startedAt:string|null;memberCount:number;milestonesTotal:number;milestonesDone:number;myOpenMilestones:number;nextMilestone:{title:string;dueDate:string|null;status:MilestoneStatus}|null;lastPostAt:string|null}

export async function listMyProjectWorkspaces():Promise<WorkspaceSummary[]>{const s=await createSupabaseServerClient();const{data,error}=await s.rpc('list_my_project_workspaces');if(error)throw new Error(error.message);return(data??[]).map((r:any)=>({projectId:r.project_id,title:r.title,slug:r.slug,projectStatus:r.project_status,publicationState:r.publication_state,membershipRole:r.membership_role,recruiting:Boolean(r.recruiting)}))}
export async function getProjectWorkspace(projectId:string):Promise<ProjectWorkspace>{const s=await createSupabaseServerClient();const{data,error}=await s.rpc('get_project_workspace',{p_project_id:projectId});if(error||!data)throw new Error(error?.message??'PROJECT_WORKSPACE_NOT_FOUND');return data as ProjectWorkspace}
export async function updateProjectMilestone(projectId:string,input:Record<string,unknown>){const title=String(input.title??'').trim();if(title.length<2)throw new Error('MILESTONE_TITLE_REQUIRED');const status=String(input.status??'TODO');const dueDate=String(input.dueDate??'').trim()||null;const s=await createSupabaseServerClient();const{data,error}=await s.rpc('upsert_project_milestone',{p_project_id:projectId,p_milestone_id:input.id||null,p_title:title,p_description:String(input.description??'').trim(),p_status:status,p_due_date:dueDate,p_sort_order:Number(input.sortOrder??100),p_assignee_user_id:input.assigneeUserId||null});if(error)throw new Error(error.message);return data}
export async function removeProjectMember(projectId:string,userId:string){const s=await createSupabaseServerClient();const{error}=await s.rpc('remove_project_member',{p_project_id:projectId,p_target_user_id:userId});if(error)throw new Error(error.message)}
export async function submitTeamProjectUpdate(projectId:string,input:Record<string,unknown>){const draft=normalizeTeamUpdateDraft(input as any);const s=await createSupabaseServerClient();const{data,error}=await s.rpc('submit_team_project_update',{p_project_id:projectId,p_title:draft.title,p_summary:draft.summary,p_body:draft.body,p_milestone:draft.milestone,p_update_date:draft.updateDate});if(error)throw new Error(error.message);return data}
export async function reviewTeamProjectUpdate(updateId:string,decision:string,feedback?:string){const s=await createSupabaseServerClient();const{data,error}=await s.rpc('review_team_project_update',{p_update_id:updateId,p_decision:decision,p_feedback:feedback?.trim()||null});if(error)throw new Error(error.message);const result=data as any;const{data:review}=await s.from('project_update_reviews').select('submitted_by_user_id,project_id').eq('project_update_id',updateId).maybeSingle();if(review){const[{data:update},{data:project},{data:member}]=await Promise.all([s.from('project_updates').select('title').eq('id',updateId).maybeSingle(),s.from('projects').select('title').eq('id',review.project_id).maybeSingle(),s.from('member_profiles').select('display_name,oberlin_email').eq('user_id',review.submitted_by_user_id).maybeSingle()]);if(member?.oberlin_email){const base=memberSiteOrigin();await sendTransactionalEmail({to:member.oberlin_email,message:projectUpdateReviewEmail({memberName:member.display_name??'there',projectTitle:project?.title??'OEC project',updateTitle:update?.title??'Project update',decision:result?.reviewStatus??'REJECTED',feedback,actionUrl:`${base}/member/teams/${review.project_id}`}),required:false})}}return data}
export async function assertTeamProjectUpdatePublishable(updateId:string,role:AdminRole){const s=await createSupabaseServerClient();const{data,error}=await s.from('project_update_reviews').select('status').eq('project_update_id',updateId).maybeSingle();if(error)throw new Error(error.message);if(!data)return false;assertTeamUpdatePublicationAllowed(role,data.status);return true}
export type AdminTeamUpdateReview={updateId:string;projectId:string;projectTitle:string;title:string;summary:string;body:string;submittedBy:string;status:string;submittedAt:string;feedback:string|null}
export async function listAdminTeamUpdateReviews():Promise<AdminTeamUpdateReview[]>{const s=await createSupabaseServerClient();const{data:reviews,error}=await s.from('project_update_reviews').select('*').in('status',['PENDING_REVIEW','CHANGES_REQUESTED','APPROVED_FOR_PUBLISH']).order('submitted_at',{ascending:true});if(error)throw new Error(error.message);const rows=reviews??[];const updateIds=rows.map(r=>r.project_update_id),projectIds=Array.from(new Set(rows.map(r=>r.project_id))),userIds=Array.from(new Set(rows.map(r=>r.submitted_by_user_id)));const[{data:updates},{data:projects},{data:members}]=await Promise.all([updateIds.length?s.from('project_updates').select('id,title,summary,body,publication_state').in('id',updateIds):Promise.resolve({data:[] as any[]}),projectIds.length?s.from('projects').select('id,title').in('id',projectIds):Promise.resolve({data:[] as any[]}),userIds.length?s.from('member_profiles').select('user_id,display_name').in('user_id',userIds):Promise.resolve({data:[] as any[]})]);const u=new Map((updates??[]).map((x:any)=>[x.id,x])),p=new Map((projects??[]).map((x:any)=>[x.id,x.title])),m=new Map((members??[]).map((x:any)=>[x.user_id,x.display_name]));return rows.filter((r:any)=>!(r.status==='APPROVED_FOR_PUBLISH'&&u.get(r.project_update_id)?.publication_state==='published')).map((r:any)=>({updateId:r.project_update_id,projectId:r.project_id,projectTitle:p.get(r.project_id)??'Project',title:u.get(r.project_update_id)?.title??'Project update',summary:u.get(r.project_update_id)?.summary??'',body:u.get(r.project_update_id)?.body??'',submittedBy:m.get(r.submitted_by_user_id)??'OEC member',status:r.status,submittedAt:r.submitted_at,feedback:r.review_feedback??null}))}

async function workspaceRpc<T=unknown>(name:string,params:Record<string,unknown>={}){const s=await createSupabaseServerClient();const{data,error}=await s.rpc(name,params);if(error)throw new Error(error.message);return data as T}
export async function listMyProjectOverview():Promise<ProjectOverview[]>{return(await workspaceRpc<ProjectOverview[]|null>('list_my_project_overview'))??[]}
export const setProjectMilestoneStatus=(milestoneId:string,status:MilestoneStatus)=>workspaceRpc('set_project_milestone_status',{p_milestone_id:milestoneId,p_status:status})
export const claimProjectMilestone=(milestoneId:string,claim:boolean)=>workspaceRpc('claim_project_milestone',{p_milestone_id:milestoneId,p_claim:claim})
export const deleteProjectMilestone=(milestoneId:string)=>workspaceRpc('delete_project_milestone',{p_milestone_id:milestoneId})
export const postProjectTeamUpdate=(projectId:string,kind:TeamPostKind,body:string)=>workspaceRpc('post_project_team_update',{p_project_id:projectId,p_kind:kind,p_body:body})
export const deleteProjectTeamPost=(postId:string)=>workspaceRpc('delete_project_team_post',{p_post_id:postId})
export const addProjectTeamLink=(projectId:string,label:string,url:string)=>workspaceRpc('add_project_team_link',{p_project_id:projectId,p_label:label,p_url:url})
export const removeProjectTeamLink=(linkId:string)=>workspaceRpc('remove_project_team_link',{p_link_id:linkId})
export const leaveProject=(projectId:string)=>workspaceRpc('leave_project',{p_project_id:projectId})
export async function resubmitTeamProjectUpdate(updateId:string,input:Parameters<typeof normalizeTeamUpdateDraft>[0]){const draft=normalizeTeamUpdateDraft(input);return workspaceRpc('resubmit_team_project_update',{p_update_id:updateId,p_title:draft.title,p_summary:draft.summary,p_body:draft.body,p_milestone:draft.milestone,p_update_date:draft.updateDate})}
