-- Projects carry a difficulty level (free text: Beginner / Intermediate /
-- Intermediate–Advanced / Advanced), shown on cards and detail pages.
alter table public.projects add column if not exists difficulty text not null default '';

-- publish_content_snapshot: add difficulty to the projects branch. Everything
-- else is unchanged from 006/018.
create or replace function public.publish_content_snapshot(p_entity_type text,p_entity_id uuid,p_payload_snapshot jsonb,p_restored_from uuid default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_version integer;v_id uuid;v_exists boolean; begin
  if p_entity_type not in ('projects','project_updates','events','opportunities','resources','news_posts','leaders','sponsors','documents','partner_schools') then raise exception 'unsupported entity type'; end if;
  if not ((private.can_publish() and private.has_scope(p_entity_type)) or coalesce(auth.role(),'')='service_role') then raise exception 'publish permission required'; end if;
  execute format('select exists(select 1 from public.%I where id=$1 for update)',p_entity_type) into v_exists using p_entity_id;
  if not v_exists then raise exception 'entity not found'; end if;
  select coalesce(max(version_number),0)+1 into v_version from public.content_versions where entity_type=p_entity_type and entity_id=p_entity_id;
  insert into public.content_versions(entity_type,entity_id,version_number,snapshot,published_by,restored_from) values(p_entity_type,p_entity_id,v_version,p_payload_snapshot,(select auth.uid()),p_restored_from) returning id into v_id;

  if p_entity_type='projects' then
    update public.projects set slug=p_payload_snapshot->>'slug',title=p_payload_snapshot->>'title',summary=coalesce(p_payload_snapshot->>'summary',''),problem=coalesce(p_payload_snapshot->>'problem',''),goal=coalesce(p_payload_snapshot->>'goal',''),discipline=coalesce(p_payload_snapshot->>'discipline',''),disciplines=coalesce(array(select jsonb_array_elements_text(p_payload_snapshot->'disciplines')),'{}'),status=p_payload_snapshot->>'status',recruiting=coalesce((p_payload_snapshot->>'recruiting')::boolean,false),skills=coalesce(array(select jsonb_array_elements_text(p_payload_snapshot->'skills')),'{}'),difficulty=coalesce(p_payload_snapshot->>'difficulty',''),lead_name=coalesce(p_payload_snapshot->>'leadName',''),next_step=coalesce(p_payload_snapshot->>'nextStep',''),team_names=coalesce(array(select jsonb_array_elements_text(p_payload_snapshot->'teamNames')),'{}'),timeline=coalesce(p_payload_snapshot->'timeline','[]'::jsonb),cover_media_id=nullif(p_payload_snapshot->>'coverMediaId','')::uuid,external_url=coalesce(p_payload_snapshot->>'externalUrl',''),github_url=coalesce(p_payload_snapshot->>'githubUrl',''),sort_order=coalesce((p_payload_snapshot->>'sortOrder')::integer,100),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='project_updates' then
    update public.project_updates set project_id=(p_payload_snapshot->>'projectId')::uuid,title=p_payload_snapshot->>'title',summary=coalesce(p_payload_snapshot->>'summary',''),body=coalesce(p_payload_snapshot->>'body',''),milestone=coalesce(p_payload_snapshot->>'milestone',''),update_date=nullif(p_payload_snapshot->>'updateDate','')::date,media_id=nullif(p_payload_snapshot->>'mediaId','')::uuid,publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='events' then
    update public.events set slug=p_payload_snapshot->>'slug',title=p_payload_snapshot->>'title',summary=coalesce(p_payload_snapshot->>'summary',''),description=coalesce(p_payload_snapshot->>'description',''),event_type=coalesce(p_payload_snapshot->>'eventType','Event'),start_at=nullif(p_payload_snapshot->>'startAt','')::timestamptz,end_at=nullif(p_payload_snapshot->>'endAt','')::timestamptz,organizer_name=coalesce(p_payload_snapshot->>'organizerName',''),location=coalesce(p_payload_snapshot->>'location',''),access_details=coalesce(p_payload_snapshot->>'accessDetails',''),registration_url=coalesce(p_payload_snapshot->>'registrationUrl',''),cover_media_id=nullif(p_payload_snapshot->>'coverMediaId','')::uuid,featured=coalesce((p_payload_snapshot->>'featured')::boolean,false),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='opportunities' then
    update public.opportunities set title=p_payload_snapshot->>'title',organization=coalesce(p_payload_snapshot->>'organization',''),opportunity_type=coalesce(p_payload_snapshot->>'opportunityType','Opportunity'),description=coalesce(p_payload_snapshot->>'description',''),deadline=nullif(p_payload_snapshot->>'deadline','')::date,location=coalesce(p_payload_snapshot->>'location',''),url=p_payload_snapshot->>'url',featured=coalesce((p_payload_snapshot->>'featured')::boolean,false),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='resources' then
    update public.resources set title=p_payload_snapshot->>'title',description=coalesce(p_payload_snapshot->>'description',''),category=coalesce(p_payload_snapshot->>'category',''),source_name=coalesce(p_payload_snapshot->>'sourceName',''),url=coalesce(p_payload_snapshot->>'url',''),source_kind=coalesce(p_payload_snapshot->>'sourceKind','club'),official_source=coalesce((p_payload_snapshot->>'officialSource')::boolean,false),source_url=coalesce(p_payload_snapshot->>'sourceUrl',''),pinned=coalesce((p_payload_snapshot->>'pinned')::boolean,false),sort_order=coalesce((p_payload_snapshot->>'sortOrder')::integer,100),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='news_posts' then
    update public.news_posts set slug=p_payload_snapshot->>'slug',title=p_payload_snapshot->>'title',excerpt=coalesce(p_payload_snapshot->>'excerpt',''),body=p_payload_snapshot->>'body',author=coalesce(p_payload_snapshot->>'author','Oberlin Engineering Club'),cover_media_id=nullif(p_payload_snapshot->>'coverMediaId','')::uuid,featured=coalesce((p_payload_snapshot->>'featured')::boolean,false),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='leaders' then
    update public.leaders set name=p_payload_snapshot->>'name',role_title=p_payload_snapshot->>'roleTitle',term=coalesce(p_payload_snapshot->>'term',''),class_year=coalesce(p_payload_snapshot->>'classYear',''),major=coalesce(p_payload_snapshot->>'major',''),bio=coalesce(p_payload_snapshot->>'bio',''),photo_media_id=nullif(p_payload_snapshot->>'photoMediaId','')::uuid,linkedin_url=coalesce(p_payload_snapshot->>'linkedinUrl',''),email=coalesce(p_payload_snapshot->>'email',''),current=coalesce((p_payload_snapshot->>'current')::boolean,true),advisor=coalesce((p_payload_snapshot->>'advisor')::boolean,false),open_seat=coalesce((p_payload_snapshot->>'openSeat')::boolean,false),sort_order=coalesce((p_payload_snapshot->>'sortOrder')::integer,100),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='sponsors' then
    update public.sponsors set name=p_payload_snapshot->>'name',relationship_type=coalesce(p_payload_snapshot->>'relationshipType','collaborator'),logo_media_id=nullif(p_payload_snapshot->>'logoMediaId','')::uuid,url=coalesce(p_payload_snapshot->>'url',''),description=coalesce(p_payload_snapshot->>'description',''),sort_order=coalesce((p_payload_snapshot->>'sortOrder')::integer,100),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='documents' then
    update public.documents set title=p_payload_snapshot->>'title',category=coalesce(p_payload_snapshot->>'category',''),description=coalesce(p_payload_snapshot->>'description',''),url=p_payload_snapshot->>'url',format=coalesce(p_payload_snapshot->>'format',''),sort_order=coalesce((p_payload_snapshot->>'sortOrder')::integer,100),publication_state='published',published_at=now() where id=p_entity_id;
  elsif p_entity_type='partner_schools' then
    update public.partner_schools set name=p_payload_snapshot->>'name',short_name=coalesce(p_payload_snapshot->>'shortName',''),location=coalesce(p_payload_snapshot->>'location',''),official_url=p_payload_snapshot->>'officialUrl',questions=coalesce(p_payload_snapshot->'questions','[]'::jsonb),sort_order=coalesce((p_payload_snapshot->>'sortOrder')::integer,100),publication_state='published',published_at=now() where id=p_entity_id;
  end if;
  insert into public.audit_log(actor_id,action,entity_type,entity_id,after_snapshot) values((select auth.uid()),case when p_restored_from is null then 'PUBLISH' else 'RESTORE' end,p_entity_type,p_entity_id::text,p_payload_snapshot);
  return v_id;
end $$;
revoke all on function public.publish_content_snapshot(text,uuid,jsonb,uuid) from public;
grant execute on function public.publish_content_snapshot(text,uuid,jsonb,uuid) to authenticated,service_role;
