import { cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { GetInvolvedForm } from '@/components/forms/GetInvolvedForm'

beforeEach(() => { Element.prototype.scrollIntoView = vi.fn() })
afterEach(() => { cleanup(); vi.unstubAllGlobals() })

describe('Spatial join flow', () => {
  it('scrolls only the tablet content when changing steps inside the 3D screen', async () => {
    const user = userEvent.setup(), scrollTo = vi.fn()
    const { container } = render(<div className="robot-terminal-content"><GetInvolvedForm/></div>)
    const tablet = container.firstElementChild as HTMLElement
    tablet.scrollTo = scrollTo
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(scrollTo).toHaveBeenCalledWith({ top: 0, behavior: 'instant' })
    expect(Element.prototype.scrollIntoView).not.toHaveBeenCalled()
  })
  it('validates details, retains interests across steps, and submits only from review', async () => {
    const user = userEvent.setup()
    const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ ok: true }) })
    vi.stubGlobal('fetch', fetch)
    render(<GetInvolvedForm/>)
    expect(screen.getByRole('heading', { name: 'Join the club' })).toBeInTheDocument()
    await user.click(screen.getByRole('checkbox', { name: 'Electronics' }))
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(screen.getByRole('heading', { name: 'Your details' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(screen.getByText('Please enter your name.')).toBeInTheDocument()
    expect(fetch).not.toHaveBeenCalled()
    await user.type(screen.getByRole('textbox', { name: 'Full name' }), 'Test Student')
    await user.type(screen.getByRole('textbox', { name: 'Email' }), 'test@example.com')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(screen.getByText('test@example.com')).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Review your request' })).toBeInTheDocument()
    expect(screen.getByText('Electronics')).toBeInTheDocument()
    expect(fetch).not.toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: 'Previous step' }))
    expect(screen.getByRole('textbox', { name: 'Full name' })).toHaveValue('Test Student')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByRole('button', { name: 'Send to OEC' }))
    expect(await screen.findByText('Request received')).toBeInTheDocument()
    const payload = JSON.parse(fetch.mock.calls[0][1].body)
    expect(payload).toMatchObject({ fullName: 'Test Student', email: 'test@example.com', interests: 'Electronics', type: 'join_club' })
    expect(fetch).toHaveBeenCalledTimes(1)
  })

  it('preserves the project deep link and recovers after a network failure', async () => {
    const user = userEvent.setup()
    const fetch = vi.fn().mockRejectedValue(new Error('offline'))
    vi.stubGlobal('fetch', fetch)
    render(<GetInvolvedForm defaultType="join_project" defaultProject="Printer repair"/>)
    expect(screen.getByRole('textbox', { name: 'Project' })).toHaveValue('Printer repair')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.type(screen.getByRole('textbox', { name: 'Full name' }), 'Test Student')
    await user.type(screen.getByRole('textbox', { name: 'Email' }), 'test@example.com')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByRole('button', { name: 'Send to OEC' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Your details are still here')
    expect(screen.getByRole('button', { name: 'Send to OEC' })).toBeEnabled()
    expect(screen.getByText('Printer repair')).toBeInTheDocument()
  })

  it('requires a project idea before proceeding with a proposal', async () => {
    const user = userEvent.setup()
    render(<GetInvolvedForm defaultType="propose_project"/>)
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Tell us what you want to build')
    expect(screen.getByRole('heading', { name: 'Propose a project' })).toBeInTheDocument()
  })

  it('routes capstone exploration through a project proposal without promising a partner', async () => {
    const user = userEvent.setup()
    const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ ok: true }) })
    vi.stubGlobal('fetch', fetch)
    render(<GetInvolvedForm defaultType="propose_project" defaultFocus="capstone"/>)
    expect(screen.getByRole('heading', { name: 'Discuss a capstone' })).toBeInTheDocument()
    expect(screen.getByText(/Confirm course requirements and academic credit with your adviser/)).toBeInTheDocument()
    await user.type(screen.getByRole('textbox', { name: 'What would you like to build?' }), 'A low-cost environmental sensor for a community garden.')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.type(screen.getByRole('textbox', { name: 'Full name' }), 'Test Student')
    await user.type(screen.getByRole('textbox', { name: 'Email' }), 'test@example.com')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(screen.getByText('Capstone exploration')).toBeInTheDocument()
    expect(fetch).not.toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: 'Send to OEC' }))
    const payload = JSON.parse(fetch.mock.calls[0][1].body)
    expect(payload.type).toBe('propose_project')
    expect(payload.message).toContain('[Capstone exploration]')
    expect(payload.projectIdea).toContain('environmental sensor')
  })

  it('does not retain the capstone tag when changing to a general membership request', async () => {
    const user = userEvent.setup()
    const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ ok: true }) })
    vi.stubGlobal('fetch', fetch)
    render(<GetInvolvedForm defaultType="propose_project" defaultFocus="capstone"/>)
    await user.selectOptions(screen.getByRole('combobox', { name: 'I would like to' }), 'join_club')
    expect(screen.getByRole('heading', { name: 'Join the club' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.type(screen.getByRole('textbox', { name: 'Full name' }), 'Test Student')
    await user.type(screen.getByRole('textbox', { name: 'Email' }), 'test@example.com')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    await user.click(screen.getByRole('button', { name: 'Send to OEC' }))
    expect(JSON.parse(fetch.mock.calls[0][1].body).message).not.toContain('Capstone')
  })
})
